run command execs into docker-compose
The use of exec gets rid of the bash process and allows signals to be propagated
into the running container, instead of being dropped by bash.

This is important to allow graceful handling of timeout, wherein a TERM signal
is sent by BK to give the running job the opportunity to tidy up and exit
cleanly before a KILL signal is ultimately sent.

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -22,6 +22,13 @@ fi
 
 [[ -n "$(plugin_read_list PUSH)" ]] && commands+=("PUSH")
 
+# run will exec into docker-compose so the push script wouldn't be called...
+if in_array "RUN" "${commands[@]}" && in_array "PUSH" "${commands[@]}"; then
+  echo "+++ Docker Compose plugin error"
+  echo "push is only allowed after build, not after run"
+  exit 1
+fi
+
 # Don't convert paths on gitbash on windows
 if is_windows ; then
   export MSYS_NO_PATHCONV=1
